#!/usr/bin/env bash
# Generate the frontend's sample-question list from data/qa_bank.json.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
node -e '
const fs = require("fs");
const bank = JSON.parse(fs.readFileSync(process.argv[1]));
const qs = bank.map(x => x.q);
const out = "// AUTO-GENERATED by scripts/sync-qa.sh. Do not edit by hand.\n" +
  "export const SAMPLE_QUESTIONS: string[] = " + JSON.stringify(qs, null, 2) + ";\n";
fs.writeFileSync(process.argv[2], out);
' "$ROOT/data/qa_bank.json" "$ROOT/web/lib/questions.ts"
echo ">> wrote web/lib/questions.ts ($(node -e 'console.log(JSON.parse(require("fs").readFileSync(process.argv[1])).length)' "$ROOT/data/qa_bank.json") questions)"
