#!/usr/bin/env bash
# Copy the compiled Subnet0 ABI into the frontend as a typed const.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ART="$ROOT/contracts/out/Subnet0.sol/Subnet0.json"

[ -f "$ART" ] || ( cd "$ROOT/contracts" && forge build >/dev/null )

node -e '
const fs = require("fs");
const art = JSON.parse(fs.readFileSync(process.argv[1]));
const body = JSON.stringify(art.abi, null, 2);
const out = "// AUTO-GENERATED by scripts/sync-abi.sh. Do not edit by hand.\n" +
  "export const SUBNET0_ABI = " + body + " as const;\n";
fs.writeFileSync(process.argv[2], out);
' "$ART" "$ROOT/web/lib/abi.ts"

echo ">> wrote web/lib/abi.ts"
